language: go

go:
  - 1.4
  - 1.4.1
  - 1.4.2
  - 1.4.3
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  # doing 'tip' is not a great idea; it has previously caused things to suddenly become "broken" based on calendar date, and i don't appreciate it.

install: true # don't `go get`, please.

script:
  - time ./goad init
  - time ./goad test
  - time ./goad test ./... -race
